---
- name: Run SonarQube container
  command: >
    docker run -d
    -p 9000:9000
    --name sonarqube
    -v sonarqube_data:/opt/sonarqube/data
    -v sonarqube_extensions:/opt/sonarqube/extensions
    -v sonarqube_logs:/opt/sonarqube/logs
    -v sonarqube_temp:/opt/sonarqube/temp
    sonarqube:latest
