---
# - name: Update apt package cache
#   apt:
#     update_cache: yes
#   become: yes
#   ignore_errors: yes

# - name: Upgrade all packages
#   apt:
#     upgrade: yes
#     autoremove: yes
#   become: yes
#   ignore_errors: yes

- name: Install oci-cli
  ansible.builtin.command:
    # cmd: sudo -H pip install oci-cli
    cmd: pip install oci-cli
  ignore_errors: yes
