---
- name: Update apt package cache
  apt:
    update_cache: yes
  become: yes
  ignore_errors: yes

- name: Upgrade all packages
  apt:
    upgrade: yes
    autoremove: yes
  become: yes
  ignore_errors: yes

- name: Install Java (Jenkins dependency)
  apt:
    name: openjdk-21-jdk
    state: present

- name: Add Jenkins repository key to the system
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present
  become: yes
  ignore_errors: yes

- name: Add the Jenkins Repo
  ansible.builtin.command:
    cmd: sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  become: yes
  ignore_errors: yes

- name: Update apt cache with new Jenkins repo
  apt:
    update_cache: yes
  become: yes
  ignore_errors: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: latest

- name: Ensure Jenkins is started and enabled
  service:
    name: jenkins
    state: started
    enabled: yes
