---
- name: Update apt package cache
  apt:
    update_cache: yes
  become: yes
  ignore_errors: yes

- name: Upgrade all packages
  apt:
    upgrade: yes
    autoremove: yes
  become: yes
  ignore_errors: yes

- name: Docker Installation step starts here !!
  apt:
    update_cache: yes
  become: yes
  ignore_errors: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  ignore_errors: yes

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: yes
  ignore_errors: yes

- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  ignore_errors: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
