---
- name: Update apt package cache
  apt:
    update_cache: yes
  become: yes
  ignore_errors: yes

- name: Upgrade all packages
  apt:
    upgrade: yes
    autoremove: yes
  become: yes
  ignore_errors: yes

- name: Ensure expect is installed
  apt:
    name: expect
    state: present
  become: yes

# - name: Add PHP 7.4 repository
#   ansible.builtin.command: sudo add-apt-repository ppa:ondrej/php

# - name: Add PHP repository
#   apt_repository:
#     repo: 'deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main'
#     state: present
#   become: yes
#   ignore_errors: yes

- name: Auto-approve adding PHP repository key
  expect:
    command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
    responses:
      'OK': ''
  become: yes

- name: Add PHP repository key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  become: yes
  ignore_errors: yes

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present
  become: yes
  ignore_errors: yes

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  become: yes
  ignore_errors: yes

- name: Update apt package cache
  apt:
    update_cache: yes
  become: yes
  ignore_errors: yes

- name: Update apt package cache
  apt:
    update_cache: yes
  become: yes
  ignore_errors: yes

- name: Install PHP 7.4
  apt:
    name: php7.4
    state: present
